### PR TITLE
describe perf-map via railroad diagrams

### PR DESCRIPTION
**Pull request by zyguan**
Signed-off-by: zyguan <zhongyangguan@gmail.com>

### CODE REVIEW

**Comment by cfzjywxk** [comment]
@zyguan @you06 
Could this be merged by now?

**Comment by zyguan** [comment]
> @zyguan @you06 Could this be merged by now?

I just propose a new way to describe performance maps. IMHO, it's easy to write and maintain for us, but I'm not sure if teammates from *Autonomous Service* can understand it.

**Comment by you06** [comment]
> I just propose a new way to describe performance maps. IMHO, it's easy to write and maintain for us, but I'm not sure if teammates from _Autonomous Service_ can understand it.

I've asked _Autonomous Service Team_, and they said it's understandable, however, it's hard for them to infer metrics formulas from railroad diagrams. Generally, they agree with switching from drawio to railroad diagrams.

**Comment by cfzjywxk** [comment]
Would it be easy to fetch metrics and formulas using railroad? I'm not familiar with it.

**Comment by zyguan** [comment]
> Would it be easy to fetch metrics and formulas using railroad? I'm not familiar with it.

We use [railroad-diagrams](https://github.com/tabatkins/railroad-diagrams/blob/gh-pages/railroad.js) to generate diagrams, it's pretty lightweight. I think we can fork/customize it and attach PromQL formulas to the diagrams (maybe display formulas on hover).

**Comment by cfzjywxk** [comment]
Looks like a good idea, we need to lower the cost of drawing a specific execution diagram, and other people could get involved in the performance-map enhacenment.

**Comment by zyguan** [comment]
I'm also thinking about to build a markdown renderer which allows us write performance maps like the following.

~~~ markdown
# TiDB Query Duration

```railroad
Diagram(
    NonTerminal("Receive packet from the client", {href: "#receive-packet-from-the-client"}),
    NonTerminal("Process query in TiDB (include TiKV)", {href: "#process-query-in-tidb"}),
)
```

- **Receive packet from the client**: The duration contains network and operation schedule latency, etc.
- **Process query in TiDB (include TiKV)**: Include all the duration TiDB executing queries and the duration sending response back to the client.

...
~~~

**Comment by you06** [comment]
> I'm also thinking about to build a markdown renderer which allows us write performance maps like the following.

That will be much better than writing JavaScript or HTML directly.

**Review by you06 — APPROVED** [review]

**Comment by cfzjywxk** [comment]
@zyguan @you06 
Does that mean we need to relink all the pages and create a new preview entry?

**Comment by you06** [comment]
> Does that mean we need to relink all the pages and create a new preview entry?

I find that there are already some `href` attributes in this PR, they take the effect of linking.

**Pull request merged**
